version: '3'

services:
  db:
    image: nouchka/sqlite3
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:3000
    volumes:
      - .:/code
    ports:
      - "3000:3000"
    depends_on:
      - db